### PR TITLE
Updated Leaderboard API controllers2

### PR DESCRIPTION
**Pull request by NitronBiohazard**
Added missing API calls in controllers.

### CODE REVIEW

**Comment by robotic-coder** [comment]
PR is merging into master 😬

**Comment by robotic-coder** [comment]
@NitronBiohazard pinging for visibility

**Comment by NitronBiohazard** [comment]
Changed to be into development instead of master

**Review by robotic-coder — CHANGES_REQUESTED** [review]
LeaderboardApiController is not calling the LeaderboardService @NitronBiohazard

**Comment by NitronBiohazard** [comment]
> 
> 
> LeaderboardApiController is not calling the LeaderboardService @NitronBiohazard

Fixed to call the LeaderboardService from the LeaderboardApiController.

**Review by robotic-coder — APPROVED** [review]

**Pull request merged**
